Done lesson 2 homework.
unDanNet/geekbrains_homework pull request #2
Opened 2021-06-19 10:56 UTC by unDanNet

2021-06-24 09:59 UTC, Infarh requested changes

2021-06-24 09:59 UTC, Infarh commented on lesson-2/Program.cs
> +        }
?

2021-06-24 09:59 UTC, Infarh commented on lesson-2/Task1.cs
> +        int GetCount();
Данный метод так и напрашивается на то, что бы быть превращённым в свойство!

2021-06-24 09:59 UTC, Infarh commented on lesson-2/Task1.cs
> +        int Last { get; }
👍

2021-06-24 09:59 UTC, Infarh commented on lesson-2/Task1.cs
> +        void AddNode(int value);
Обычно методы добавления элемента в связный список возвращают обратно созданный ими узел этого списка.

2021-06-24 09:59 UTC, Infarh commented on lesson-2/Task1.cs
> +        void AddNode(int value);
И обычно делается два метода: добавление в начало и добавление в конец списка.

2021-06-24 09:59 UTC, Infarh commented on lesson-2/Task1.cs
> +        void RemoveNode(int index);
А методы удаления обычно возвращают bool - удалось, или нет удалить элемент.

2021-06-24 09:59 UTC, Infarh commented on lesson-2/Task1.cs
> +        public Node PrevNode { get; set; }
Данные свойства у узла списка обычно должны быть реализованы таким образом, чтобы изменить их мог только список, которому данный узел принадлежит. И ни кто более.

2021-06-24 09:59 UTC, Infarh commented on lesson-2/Task1.cs
> +        }
Лучше всё же было бы сделать свойства, возвращающие сам первый/последний элемент списка.

2021-06-24 09:59 UTC, Infarh commented on lesson-2/Task1.cs
> +            lastNode = null;
Бессмысленно. При создании нового объекта эти значения и так будут в данных полях.

2021-06-24 09:59 UTC, Infarh commented on lesson-2/Task1.cs
> +                firstNode = new Node {Value = value, NextNode = null, PrevNode = null};
```suggestion
                firstNode = new Node {Value = value};
```

2021-06-24 09:59 UTC, Infarh commented on lesson-2/Task1.cs
> +            var node = new Node {Value = value, NextNode = null, PrevNode = lastNode};
```suggestion
            var node = new Node {Value = value, PrevNode = lastNode};
```

2021-06-24 09:59 UTC, Infarh commented on lesson-2/Task1.cs
> +                firstNode = new Node {Value = value, NextNode = null, PrevNode = null};
Тавтология, как и со случаем конструктора

2021-06-24 09:59 UTC, Infarh commented on lesson-2/Task1.cs
> +                var newNode = new Node {Value = value, NextNode = null, PrevNode = lastNode};
```suggestion
                var newNode = new Node {Value = value, PrevNode = lastNode};
```

2021-06-24 09:59 UTC, Infarh commented on lesson-2/Task1.cs
> +            var searchResult = FindNode(node);
Зачем? Уже ведь указан узел, после которого надо вставить требуемое значение. Это должно быть выполнено за O(1) без перебора существующих элементов списка.

2021-06-24 09:59 UTC, Infarh commented on lesson-2/Task1.cs
> +            return current == lastNode ? null : current;
Вот это вообще непонятно зачем здесь... Это убивает весь смысл использования данной структуры данных. Необходимость метода FindNode была бы оправдана если бы в качестве параметра передавалось бы значение. Но если есть ссылка, то зачем что-то искать? Если у Вас было целью проверить принадлежность узла списку, то почему бы просто в каждом узле не предусмотреть поле/свойство, в которое бы список записывал бы ссылку на самого себя при создании узла. И тогда можно было бы проверять - принадлежит ли узел списку, или нет.

2021-06-24 09:59 UTC, Infarh commented on lesson-2/Task1.cs
> +                return current.Value;
А есть же метод поиска узла по его индексу с O(N/2). Зачем повторяться?

2021-06-24 10:15 UTC, unDanNet commented on lesson-2/Program.cs
> +        }
А что в мейн писать-то? Тесты у меня сделаны в виде юнит тестов, так что для мейна ничего и не остается....

2021-06-24 10:17 UTC, unDanNet commented on lesson-2/Task1.cs
> +        int GetCount();
Согласен, но просто я думал, что надо реализовывать согласно интерфейсу, который в методичке. Вот я и делал всё согласно интерфейсу.

2021-06-24 10:21 UTC, unDanNet commented on lesson-2/Task1.cs
> +        void AddNode(int value);
Тут тоже все упирается в интерфейс, который был в методичке. Вы сразу тогда скажите, этот интерфейс из методички имеет какой-то смысл, или лучше уж написать свой со всеми необходимыми методами? Просто мне этот интерфейс в принципе не понравился, какие-то странные методы, которые принимает в качестве аргумента ноды. Нормальные списки же вообще таким не страдают

2021-06-24 10:21 UTC, unDanNet commented on lesson-2/Task1.cs
> +        void RemoveNode(int index);
См. выше  ответ про интерфейс.

2021-06-24 10:25 UTC, unDanNet commented on lesson-2/Task1.cs
> +        }
Я сначала думал так, но мне совсем не нравится идея давать возможность оперировать нодами пользователю, ведь он же так может с ссылками что-то сделать и в итоге список сломать вообще

2021-06-24 10:26 UTC, unDanNet commented on lesson-2/Task1.cs
> +            lastNode = null;
Привычка после С++, надо отучиваться

2021-06-24 10:28 UTC, unDanNet commented on lesson-2/Task1.cs
> +            var searchResult = FindNode(node);
А если пользователь передаст какую-то ноду, которую он создал просто так, а не которая есть в списке?
Поэтому и выполняю проверку, есть ли вообще такая нода, иначе вся вставка не будет иметь смысла.

2021-06-24 10:29 UTC, unDanNet commented on lesson-2/Task1.cs
> +            return current == lastNode ? null : current;
Тут согласен, наверно поле в ноде было бы более оптимальным решением для проверки, нежели такой метод

2021-06-24 10:30 UTC, unDanNet commented on lesson-2/Task1.cs
> +                return current.Value;
Ой, я вроде бы сделал оператор индексирования до метода поиска по индексу и забыл вообще про его существование потом. Да, тут надо было вызвать метод, согласен

2021-06-24 12:09 UTC, Infarh commented on lesson-2/Task1.cs
> +            return current == lastNode ? null : current;
Запретить создавать узлы всем, Кому ни поподя. Закрыть конструктор. А в сам узел добавить скрытое поле, в которое заносить список, которому этот узел принадлежит.

2021-06-24 12:09 UTC, Infarh commented on lesson-2/Task1.cs
> +            var searchResult = FindNode(node);
Запретить создавать узлы всем, Кому ни поподя. Закрыть конструктор. А в сам узел добавить скрытое поле, в которое заносить список, которому этот узел принадлежит.

2021-06-24 12:10 UTC, Infarh commented on lesson-2/Task1.cs
> +        int GetCount();
Логично.

2021-06-24 12:12 UTC, Infarh commented on lesson-2/Task1.cs
> +        void AddNode(int value);
Стандартный класс очень даже "страдает"
![image](https://user-images.githubusercontent.com/595602/123260734-94503c00-d4fe-11eb-8b47-7d7fdfd62a90.png)

2021-06-26 16:33 UTC, unDanNet commented on lesson-2/Task1.cs
> +        void AddNode(int value);
Ой, а я не знал, что есть встроенный линкедЛист, тогда прошу прощения, вы правы!

2021-07-01 13:20 UTC, merged